// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNuxGocrlFlnR3vzGWqnnhaxNeVlxo_dc',
    appId: '1:76044902120:web:87d67a4273aca9f9aaf35d',
    messagingSenderId: '76044902120',
    projectId: 'auconnect-10d2e',
    authDomain: 'auconnect-10d2e.firebaseapp.com',
    storageBucket: 'auconnect-10d2e.firebasestorage.app',
    measurementId: 'G-WNBVT2RG5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV_oea225PeQBwvgPLLvMZcR1ukXehGpM',
    appId: '1:76044902120:android:e012aba6f8a76ab6aaf35d',
    messagingSenderId: '76044902120',
    projectId: 'auconnect-10d2e',
    storageBucket: 'auconnect-10d2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTFrlUs8FReVCMxvGumG6H-9JXdUOci-M',
    appId: '1:76044902120:ios:6cca93fe6c4384cfaaf35d',
    messagingSenderId: '76044902120',
    projectId: 'auconnect-10d2e',
    storageBucket: 'auconnect-10d2e.firebasestorage.app',
    iosBundleId: 'com.example.auConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTFrlUs8FReVCMxvGumG6H-9JXdUOci-M',
    appId: '1:76044902120:ios:6cca93fe6c4384cfaaf35d',
    messagingSenderId: '76044902120',
    projectId: 'auconnect-10d2e',
    storageBucket: 'auconnect-10d2e.firebasestorage.app',
    iosBundleId: 'com.example.auConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNuxGocrlFlnR3vzGWqnnhaxNeVlxo_dc',
    appId: '1:76044902120:web:3bad922abc9e27e6aaf35d',
    messagingSenderId: '76044902120',
    projectId: 'auconnect-10d2e',
    authDomain: 'auconnect-10d2e.firebaseapp.com',
    storageBucket: 'auconnect-10d2e.firebasestorage.app',
    measurementId: 'G-K07FCLZCY8',
  );
}
